### PR TITLE
Added new test for owasp-masvs V5.1

### PR DESCRIPTION
**Pull request by krsoninikhil**
Added an activity which renders `example.com` once with `http` and once with `https` as a test case for [OWASP-MASVS V5.1](https://github.com/OWASP/owasp-masvs/blob/master/Document/0x10-V5-Network_communication_requirements.md)

PS: Should the `.gitignore` file be updated?

### CODE REVIEW

**Comment by krsoninikhil** [comment]
I changed added a `.gitignore` in app's root, please have look.

**Comment by sushi2k** [comment]
Hi Nikhil, thanks for the first pull request in the Hacking Playground :-)

Can you please do the pull request again and only add the following files:

Android/OMTG-Android-App/app/src/main/java/sg/vp/owasp_mobile/OMTG_Android/MyActivity.java
Android/OMTG-Android-App/app/src/main/java/sg/vp/owasp_mobile/OMTG_Android/OMTG_NETW_001_Secure_Channel.java
Android/OMTG-Android-App/app/src/main/res/layout/activity_omtg__netw_001__secure__channel.xml
Android/OMTG-Android-App/app/src/main/res/layout/content_my.xml
Android/OMTG-Android-App/app/src/main/res/layout/content_omtg__netw_001__secure__channel.xml
Android/OMTG-Android-App/app/src/main/res/values/strings.xml

Or you update your .gitignore to:
*.iml
.idea/workspace.xml
.idea/tasks.xml
.idea/gradle.xml
.idea/dictionaries
.idea/libraries
.gradle/
build/

Otherwise too much files are changed.

**Comment by krsoninikhil** [comment]
Thank you @sushi2k for reviewing, I'll change it as mentioned.

**Comment by krsoninikhil** [comment]
But shouldn't the files you mentioned for `.gitignore` be removed from this repo as well?

**Pull request merged**
